# Generated by Django 5.0.6 on 2024-07-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0004_perfume_woman_usuario_alter_perfume_inspiracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfume',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='perfume_woman',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='acerca_de',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
