# Generated by Django 5.0.6 on 2024-07-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0005_alter_perfume_options_alter_perfume_woman_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='acerca_de',
            new_name='sobre_mi',
        ),
    ]
