# Generated by Django 5.0.6 on 2024-07-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0007_usuario_github_url_usuario_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_perfil', models.ImageField(default='Error.', upload_to='usuario/')),
                ('nombre_completo', models.CharField(default='Nombre no disponible', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sobre_mi', models.TextField(blank=True, default='', null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
