# Generated by Django 5.0.6 on 2024-07-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0008_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='descripcion',
            field=models.TextField(default='Descripción'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='inspiracion',
            field=models.CharField(default='Nombre Inspiracion', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='nombre',
            field=models.CharField(default='Nombre de perfume', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfume_woman',
            name='descripcion',
            field=models.TextField(default='Descripción'),
        ),
        migrations.AlterField(
            model_name='perfume_woman',
            name='inspiracion',
            field=models.CharField(default='Nombre Inspiracion', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfume_woman',
            name='nombre',
            field=models.CharField(default='Nombre de perfume', max_length=100),
        ),
    ]
