# Generated by Django 5.0.6 on 2024-07-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0010_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='sobre_mi',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
