# Generated by Django 5.0.6 on 2024-07-12 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zar', '0011_remove_usuario_sobre_mi_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default=datetime.datetime(2024, 7, 12, 3, 1, 29, 461796, tzinfo=datetime.timezone.utc), max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen_usuario',
            field=models.ImageField(default='usuario/default.png', upload_to='usuario/'),
        ),
    ]
